version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/go:1.19.2

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: make dependencies
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Install tools
          command: make prepare
      - run:
          name: Build
          command: make build
      - run:
          name: Static analysis - vet
          command: make vet
      - run:
          name: Static analysis - staticcheck
          command: make lint
      - run:
          name: Test - unit
          command: make test
      - run:
          name: Test - integration
          command: make it

workflows:
  buildAndTest:
    jobs:
      - build
