# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", ">= 4.3.4"
gem "kramdown-parser-gfm"
gem "jekyll-theme-eugene-sy", :git => "git@github.com:eugene-sy/jekyll-theme-eugene-sy.git"
